# Generated by Django 6.0.5 on 2026-07-23 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='idx_student_id_no'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department', 'semester'], name='idx_student_dept_sem'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='idx_student_status'),
        ),
    ]
