# Generated by Django 6.0.5 on 2026-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['student', 'status'], name='idx_fee_student_status'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['due_date'], name='idx_fee_due_date'),
        ),
    ]
