"""
Custom Authentication for the Chatbot API.

The frontend uses mock JWT tokens generated by the Supabase-based client.js,
which are not valid simplejwt tokens. This custom authenticator handles both
real JWT tokens and mock tokens by falling back to user lookup via
X-User-Email / X-User-ID headers.

When a Supabase user doesn't exist in Django's local DB, the authenticator
auto-creates them to keep both systems in sync.
"""
import logging
from rest_framework import authentication, exceptions
from django.contrib.auth import get_user_model

logger = logging.getLogger(__name__)
User = get_user_model()


class ChatBotAuthentication(authentication.BaseAuthentication):
    """
    Custom authentication that supports:
    1. Real JWT tokens (via simplejwt) — for production
    2. Mock tokens (from Supabase client) — for development
    
    When a mock token is detected, it uses X-User-Email and X-User-ID
    headers to identify (and optionally auto-create) the user.
    """

    def authenticate(self, request):
        auth_header = request.headers.get('Authorization', '')

        if not auth_header.startswith('Bearer '):
            return None  # No auth header, let other authenticators handle it

        token = auth_header.split(' ', 1)[1].strip()

        # 1. Try real JWT authentication first
        try:
            from rest_framework_simplejwt.authentication import JWTAuthentication
            jwt_auth = JWTAuthentication()
            result = jwt_auth.authenticate(request)
            if result:
                return result
        except Exception:
            pass  # Token is not a valid JWT, try mock auth

        # 2. Handle mock tokens from the Supabase-based frontend
        if token.startswith('mock_access_token_'):
            return self._authenticate_mock_token(request)

        return None

    def _authenticate_mock_token(self, request):
        """
        Authenticates using mock tokens by looking up the user via
        X-User-Email or X-User-ID headers sent by the frontend.
        Auto-creates the Django user if they exist in Supabase but not locally.
        """
        email = request.headers.get('X-User-Email', '').strip()
        user_id = request.headers.get('X-User-ID', '').strip()
        first_name = request.headers.get('X-User-FirstName', '').strip()
        last_name = request.headers.get('X-User-LastName', '').strip()
        role = request.headers.get('X-User-Role', 'student').strip().lower()

        if not email and not user_id:
            raise exceptions.AuthenticationFailed(
                'Mock token detected but no user identification headers provided.'
            )

        user = None

        # Try to find user by email first (most reliable cross-system identifier)
        if email:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                pass

        # Fallback: try by integer ID (only if it looks like an integer)
        if not user and user_id:
            try:
                uid = int(user_id)
                user = User.objects.get(id=uid)
            except (ValueError, User.DoesNotExist):
                pass

        # Auto-create user if they exist in Supabase but not in Django
        if not user and email:
            logger.info(f"Auto-creating Django user for Supabase email: {email}")
            username = email.split('@')[0].replace('.', '_')
            user = User.objects.create(
                email=email,
                username=username,
                first_name=first_name or username.split('_')[0].title(),
                last_name=last_name or '',
                role=role,
            )
            user.set_unusable_password()
            user.save()

            # Try to create a student profile if role is student
            if role == 'student':
                try:
                    from students.models import Student
                    if not hasattr(user, 'student_profile'):
                        Student.objects.create(
                            user=user,
                            student_id=username.upper(),
                            year_of_study=1,
                            semester=1,
                            status='active',
                        )
                except Exception as e:
                    logger.warning(f"Could not auto-create student profile: {e}")

        if not user:
            raise exceptions.AuthenticationFailed('User not found and could not be auto-created.')

        logger.debug(f"Mock auth successful for user: {user.get_full_name()} ({user.email})")
        return (user, None)
