# Generated by Django 6.0.6 on 2026-07-24 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('courses', '0001_initial'),
        ('faculty', '0001_initial'),
        ('students', '0002_student_idx_student_id_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching', models.PositiveSmallIntegerField(default=3)),
                ('knowledge', models.PositiveSmallIntegerField(default=3)),
                ('communication', models.PositiveSmallIntegerField(default=3)),
                ('punctuality', models.PositiveSmallIntegerField(default=3)),
                ('comment', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='courses.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='faculty.faculty')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_feedback', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
