# Generated by Django 6.0.6 on 2026-07-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_parent'),
        ('courses', '0001_initial'),
        ('students', '0002_student_idx_student_id_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('registered', 'Registered'), ('cleared', 'Cleared')], default='active', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=1)),
                ('reexam_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlogs', to='students.student')),
            ],
            options={
                'ordering': ['status', '-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
