# Generated by Django 6.0.6 on 2026-07-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_backlog'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term'), ('endsem', 'End-Semester'), ('practical', 'Practical'), ('quiz', 'Quiz'), ('viva', 'Viva')], default='endsem', max_length=12)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('building', models.CharField(blank=True, max_length=50)),
                ('max_marks', models.PositiveSmallIntegerField(default=100)),
                ('seats_per_room', models.PositiveSmallIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='courses.course')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
