# Generated by Django 6.0.6 on 2026-07-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0006_book_bookloan'),
        ('students', '0002_student_idx_student_id_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('academic', 'Academic'), ('social', 'Social / Volunteering'), ('other', 'Other')], default='technical', max_length=12)),
                ('level', models.CharField(choices=[('college', 'College'), ('state', 'State'), ('national', 'National'), ('international', 'International')], default='college', max_length=15)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('date_awarded', models.DateField()),
                ('position', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('verification', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='students.student')),
            ],
            options={
                'ordering': ['-date_awarded', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('work_mode', models.CharField(choices=[('onsite', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='onsite', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stipend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, max_length=300)),
                ('certificate_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10)),
                ('verification', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='students.student')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
