# Generated by Django 6.0.6 on 2026-07-25 08:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_achievement_internship'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_approve_leaves', models.BooleanField(default=True)),
                ('can_manage_timetable', models.BooleanField(default=False)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='faculty.faculty')),
                ('delegator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='faculty.faculty')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='faculty.department')),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
