# Generated by Django 6.0.6 on 2026-07-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='ai_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='ai_answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='ai_confidence',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doubt',
            name='ai_helpful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doubt',
            name='ai_sources',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='doubt',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('ai_answered', 'AI Answered'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20),
        ),
    ]
