# Generated by Django 6.0.6 on 2026-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sector', models.CharField(default='IT', max_length=50)),
                ('package_lpa', models.DecimalField(decimal_places=1, default=6.0, max_digits=5)),
                ('min_cpi', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('max_backlogs', models.PositiveSmallIntegerField(default=0)),
                ('min_attendance', models.DecimalField(decimal_places=2, default=75.0, max_digits=5)),
                ('roles', models.CharField(blank=True, max_length=200)),
                ('bond_years', models.PositiveSmallIntegerField(default=0)),
                ('other_criteria', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Placement companies',
                'ordering': ['-package_lpa', 'name'],
            },
        ),
    ]
